export const ACTIONSTYPES = {
    ALL_PRODUCTS:'ALL_PRODUCTS',
    SELECTED_PRODUCT:'SELECTED_PRODUCT',
    REMOVE_FROM_CART:'REMOVE_FROM_CART',
    QUANTITY:'QUANTITY',
    ADD_TO_CART:'ADD_TO_CART'
}